version: '3.4'

services:
  api:
    image: node:10-alpine
    user: node
    volumes:
    - ./api:/var/app
    - ./.docker/api:/opt/docker
    ports:
    - 3001:3001
    working_dir: /var/app
    command: /opt/docker/start.sh
  front:
    image: node:10-alpine
    user: node
    volumes:
    - ./front:/var/app
    - ./.docker/front:/opt/docker
    ports:
    - 3000:3000
    - 35729:35729
    working_dir: /var/app
    command: /opt/docker/start.sh
